export enum Links {
  logo = "/images/logo.png",
  myPhoto = "/images/myPhoto.jpg",
  design = "/images/design.png",
  frontend = "/images/frontend.png",
  backend = "/images/backend.png",
  datax = "/images/datax.png",
  dugood = "/images/dugood.png",
  ergotech = "/images/ergotech.png",
  innopolis = "/images/innopolis.png",
  jalgroup = "/images/jalgroup.png",
  tunuk = "/images/tunuk.png",
  mainImage = "/images/mainImage.png",
  email = "/images/email.png",
  instagram = "/images/instagram.png",
  linkedin = "/images/linkedin.png",
  telegram = "/images/telegram.png",
  whatsapp = "/images/whatsapp.png",
  github = "/images/git.png"
}
